import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Decors(props) {
  const { nodes, materials } = useGLTF('/assets/3DModels/DECORS.glb')
  return ( 
     <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Broken_roof'].geometry}
        material={materials['WoodHandle.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Destroyed'].geometry}
        material={materials['WoodBeam.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+dest'].geometry}
        material={materials['WoodBeam.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Boat'].geometry}
        material={materials['Boat_texture.001']}
        position={[-0.03, 0.541, -3.491]}
      />
      <group position={[0.83, -0.533, 6.138]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['+Bridge_1'].geometry}
          material={materials.bridge_wood05}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['+Bridge_2'].geometry}
          material={materials['BRIDGE MAT']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+river'].geometry}
        material={materials['Material.015']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+scarecrow'].geometry}
        material={materials.scarecrow_material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+tronk'].geometry}
        material={materials['Material.003']}
        position={[29.045, 3.761, -10.396]}
        rotation={[-Math.PI / 2, 0, -1.458]}
        scale={0.371}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house3_1'].geometry}
        material={materials['WoodPlank.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house3_2'].geometry}
        material={materials['WoodBark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house4_1'].geometry}
        material={materials['WoodBark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house4_2'].geometry}
        material={materials['Thatch.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house4_3'].geometry}
        material={materials['WoodPlank.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house_1'].geometry}
        material={materials['Black.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house_2'].geometry}
        material={materials['WoodPlank.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house_3'].geometry}
        material={materials['WoodBark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house2_1'].geometry}
        material={materials['WoodPlank.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+house2_2'].geometry}
        material={materials['WoodBark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Ruins_1'].geometry}
        material={materials['WoodPlank.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Ruins_2'].geometry}
        material={materials['WoodBark.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_dest_1'].geometry}
        material={materials['WoodBeam.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_dest_2'].geometry}
        material={materials['WoodWall.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_dest_3'].geometry}
        material={materials.AxeHead}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_dest_4'].geometry}
        material={materials['WoodPlank.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_des1'].geometry}
        material={materials['WoodBeam.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_des1_1'].geometry}
        material={materials['WoodPlank.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+BigHouse_des1_2'].geometry}
        material={materials['WoodWall.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+dest_house_1'].geometry}
        material={materials['Thatch.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+dest_house_2'].geometry}
        material={materials['WoodBeam.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Tent_dest_1'].geometry}
        material={materials['Straw.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Tent_dest_2'].geometry}
        material={materials.Straw}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Tent_dest_3'].geometry}
        material={materials['WoodPlank.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Tent_dest_4'].geometry}
        material={materials['WoodBark.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+barac_1'].geometry}
        material={materials['WoodDark.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+barac_2'].geometry}
        material={materials['WoodHandle.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_1'].geometry}
        material={materials.CutStone}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_2'].geometry}
        material={materials.autumn_yellow_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_3'].geometry}
        material={materials['rock_1_material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_4'].geometry}
        material={materials.rock_2_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_5'].geometry}
        material={materials.grass3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_6'].geometry}
        material={materials.grass1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_7'].geometry}
        material={materials.grass2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_8'].geometry}
        material={materials['Material.007']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+ROCKSALL2_9'].geometry}
        material={materials['material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Pointer_1'].geometry}
        material={materials['material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+Pointer_2'].geometry}
        material={nodes['+Pointer_2'].material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+LeafsALL001_1'].geometry}
        material={materials.leafs_mat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['+LeafsALL001_2'].geometry}
        material={materials['autumn_yellow_mat.001']}
      />
    </group>
  )
}

useGLTF.preload('/assets/3DModels/DECORS.glb')