/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";

export default function Terrain(props) {
  const { nodes, materials } = useGLTF("/terrain_textured.glb");
  // useEffect(() => {
  //   scene.traverse((child) => {
  //     if (child.isMesh) {
  //       child.castShadow = true;
  //       child.receiveShadow = true;
  //     }
  //   });
  // }, [scene]);

  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          // castShadow={true}
          // receiveShadow={true}
          geometry={nodes.Plane004.geometry}
          material={materials["Material.001"]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/terrain_textured.glb");
