// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { RigidBody } from "@react-three/rapier";
// import * as THREE from "three";

// export default function Terrain(props) {
//   const { nodes, materials } = useGLTF("/ground.glb");

//   return (
//     <group {...props} dispose={null} position={[0, 0, 0]}>
//       <RigidBody type="fixed" colliders="trimesh">
//         <mesh
//           castShadow
//           receiveShadow  
//         />
//       </RigidBody>
//     </group>
//   );
// }

// useGLTF.preload("/ground.glb");


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Terrain(props) {
  const { nodes, materials } = useGLTF('/assets/3DModels/all cleaned up1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="===TERRAIN===001"
        castShadow
        receiveShadow
        geometry={nodes['===TERRAIN===001'].geometry}
        material={materials['Material.001']}
      />
      <mesh
        name="+Tronk"
        castShadow
        receiveShadow
        geometry={nodes['+Tronk'].geometry}
        material={materials['Material.005']}
      />
      <mesh
        name="+river"
        castShadow
        receiveShadow
        geometry={nodes['+river'].geometry}
        material={materials['Material.015']}
      />
      <mesh
        name="Text004"
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={nodes.Text004.material}
      />
      <mesh
        name="Text004_1"
        castShadow
        receiveShadow
        geometry={nodes.Text004_1.geometry}
        material={materials['material.001']}
      />
      <mesh
        name="Text004_2"
        castShadow
        receiveShadow
        geometry={nodes.Text004_2.geometry}
        material={materials.scarecrow_material}
      />
      <mesh
        name="Text004_3"
        castShadow
        receiveShadow
        geometry={nodes.Text004_3.geometry}
        material={materials.rock_2_mat}
      />
      <mesh
        name="Text004_4"
        castShadow
        receiveShadow
        geometry={nodes.Text004_4.geometry}
        material={materials['Material.007']}
      />
      <mesh
        name="Text004_5"
        castShadow
        receiveShadow
        geometry={nodes.Text004_5.geometry}
        material={materials['material.002']}
      />
      <mesh
        name="Text004_6"
        castShadow
        receiveShadow
        geometry={nodes.Text004_6.geometry}
        material={materials['rock_1_material.002']}
      />
      <mesh
        name="Text004_7"
        castShadow
        receiveShadow
        geometry={nodes.Text004_7.geometry}
        material={materials.autumn_yellow_mat}
      />
      <mesh
        name="Text004_8"
        castShadow
        receiveShadow
        geometry={nodes.Text004_8.geometry}
        material={materials.grass3}
      />
      <mesh
        name="Text004_9"
        castShadow
        receiveShadow
        geometry={nodes.Text004_9.geometry}
        material={materials.grass1}
      />
      <mesh
        name="Text004_10"
        castShadow
        receiveShadow
        geometry={nodes.Text004_10.geometry}
        material={materials.grass2}
      />
      <mesh
        name="Text004_11"
        castShadow
        receiveShadow
        geometry={nodes.Text004_11.geometry}
        material={materials.leafs_mat}
      />
      <mesh
        name="Text004_12"
        castShadow
        receiveShadow
        geometry={nodes.Text004_12.geometry}
        material={materials['WoodDark.001']}
      />
      <mesh
        name="Text004_13"
        castShadow
        receiveShadow
        geometry={nodes.Text004_13.geometry}
        material={materials['WoodHandle.001']}
      />
      <mesh
        name="Text004_14"
        castShadow
        receiveShadow
        geometry={nodes.Text004_14.geometry}
        material={materials['WoodBeam.003']}
      />
      <mesh
        name="Text004_15"
        castShadow
        receiveShadow
        geometry={nodes.Text004_15.geometry}
        material={materials['WoodWall.001']}
      />
      <mesh
        name="Text004_16"
        castShadow
        receiveShadow
        geometry={nodes.Text004_16.geometry}
        material={materials.AxeHead}
      />
      <mesh
        name="Text004_17"
        castShadow
        receiveShadow
        geometry={nodes.Text004_17.geometry}
        material={materials['WoodPlank.003']}
      />
      <mesh
        name="Text004_18"
        castShadow
        receiveShadow
        geometry={nodes.Text004_18.geometry}
        material={materials['WoodBeam.001']}
      />
      <mesh
        name="Text004_19"
        castShadow
        receiveShadow
        geometry={nodes.Text004_19.geometry}
        material={materials['Thatch.005']}
      />
      <mesh
        name="Text004_20"
        castShadow
        receiveShadow
        geometry={nodes.Text004_20.geometry}
        material={materials['Straw.001']}
      />
      <mesh
        name="Text004_21"
        castShadow
        receiveShadow
        geometry={nodes.Text004_21.geometry}
        material={materials.Straw}
      />
      <mesh
        name="Text004_22"
        castShadow
        receiveShadow
        geometry={nodes.Text004_22.geometry}
        material={materials['WoodPlank.005']}
      />
      <mesh
        name="Text004_23"
        castShadow
        receiveShadow
        geometry={nodes.Text004_23.geometry}
        material={materials['WoodBark.002']}
      />
      <mesh
        name="Text004_24"
        castShadow
        receiveShadow
        geometry={nodes.Text004_24.geometry}
        material={materials['Boat_texture.001']}
      />
      <mesh
        name="Text004_25"
        castShadow
        receiveShadow
        geometry={nodes.Text004_25.geometry}
        material={materials.CutStone}
      />
      <mesh
        name="Text004_26"
        castShadow
        receiveShadow
        geometry={nodes.Text004_26.geometry}
        material={materials['WoodHandle.004']}
      />
      <mesh
        name="Text004_27"
        castShadow
        receiveShadow
        geometry={nodes.Text004_27.geometry}
        material={materials['WoodPlank.002']}
      />
      <mesh
        name="Text004_28"
        castShadow
        receiveShadow
        geometry={nodes.Text004_28.geometry}
        material={materials['WoodBark.001']}
      />
      <mesh
        name="Text004_29"
        castShadow
        receiveShadow
        geometry={nodes.Text004_29.geometry}
        material={materials['Black.001']}
      />
      <mesh
        name="Text004_30"
        castShadow
        receiveShadow
        geometry={nodes.Text004_30.geometry}
        material={materials['WoodPlank.001']}
      />
      <mesh
        name="Text004_31"
        castShadow
        receiveShadow
        geometry={nodes.Text004_31.geometry}
        material={materials['WoodBark.004']}
      />
      <mesh
        name="Text004_32"
        castShadow
        receiveShadow
        geometry={nodes.Text004_32.geometry}
        material={materials['WoodPlank.004']}
      />
      <mesh
        name="Text004_33"
        castShadow
        receiveShadow
        geometry={nodes.Text004_33.geometry}
        material={materials['WoodWall.004']}
      />
      <mesh
        name="Text004_34"
        castShadow
        receiveShadow
        geometry={nodes.Text004_34.geometry}
        material={materials.bridge_wood05}
      />
      <mesh
        name="Text004_35"
        castShadow
        receiveShadow
        geometry={nodes.Text004_35.geometry}
        material={materials['BRIDGE MAT']}
      />
      <mesh
        name="Text004_36"
        castShadow
        receiveShadow
        geometry={nodes.Text004_36.geometry}
        material={materials['Thatch.002']}
      />
    </group>
  )
}

useGLTF.preload('/assets/3DModels/all cleaned up1.glb')