/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";

export default function Terrain(props) {
  const { nodes, materials } = useGLTF("/terrain_textured.glb");

  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004.geometry}
          material={materials["Material.001"]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("/terrain_textured.glb");
