export const c_Arbre_HotSpots = [
	{
		image: "/assets/images/MIL_Saisons.png",
		title: "Le bois raconte le climat",
		text: "Le climat influence la variation annuelle dans la croissance du bois. Les cernes sont très étroits en raison d’une sécheresse qui frappe la région. Si la sécheresse perdure plusieurs années, on retrouvera une série de cernes qui seront consécutivement très étroits. Cela nous renseigne sur la durée et la gravité de l’évènement climatique.",
		mustBeFound: false,
		x: -450,
		y: 300,
	},
	{
		image: "/assets/images/MIL_Feu.png",
		title: "Une cicatrice de feu révélatrice",
		text: "L’écorce environnante a été altérée par un incendie. Le bois présente une teinte plus sombre. Selon la durée de l’exposition au feu et la proximité des flammes, son degré d’altération varie. Ce type d’anomalie constitue un indice d’intervention humaine.",
		mustBeFound: true,
		x: -200,
		y: 100,
	},
	{
		image: "/assets/images/MIL_Age.png",
		title: "Les cernes du temps : l’âge révélé",
		text: "Les cernes de croissance d’un arbre permettent de déterminer son âge, chaque anneau correspondant généralement à une année de développement. L’arbre découvert par Soren a plus de 130 ans",
		mustBeFound: true,
		x: 100,
		y: 200,
	},
	{
		image: "/assets/images/MIL_Insectes.png",
		title: "Les insectes impactent la vie de l’arbre",
		text: "La croissance est faible et les anneaux sont très rapprochés avec une coupure ce qui signifie d’une infestation d’insectes.",
		mustBeFound: false,
		x: 300,
		y: -100,
	},
	{
		image: "/assets/images/MIL_Balle.png",
		title: "Les arbres portent les traces des conflits",
		text: "L’écorce de l’arbre présente un impact, on observe une balle de pistolet, vraisemblablement dû à une intervention humaine lors d’une guerre.",
		mustBeFound: true,
		x: 200,
		y: -300,
	},
	{
		image: "/assets/images/MIL_Balle.png",
		title: "Coupe nette ou chute brute : qui est le responsable ?",
		text: "Lorsqu’un arbre est abattu, la coupe est nette, lisse et régulière, avec des cernes bien visibles et intactes. À l’inverse, un arbre tombé de lui-même présente une cassure irrégulière : le bois est arraché, les fibres sont déchirées et il peut manquer une partie du tronc du côté où il a chuté, les cernes sont souvent abîmées ou incomplètes.",
		mustBeFound: true,
		x: -100,
		y: -200,
	},
];