/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Terrain(props) {
  const { nodes, materials } = useGLTF("/terrain_textured.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/terrain_textured.glb");
